/**
 * Fibonacci sequence
 * 
 * The Fibonacci sequence is a series of numbers where each number is the sum 
 * of the two preceding ones, usually starting with 0 and 1.
 * For example: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ...
 * 
 * Algorithm:
 * 1. Start with first two numbers 0 and 1
 * 2. Next number is generated by adding previous two numbers
 * 3. First number becomes second number
 * 4. Second number becomes the next number
 * 5. Repeat steps 2-4 for n times

 */


#include <iostream>
using namespace std;

int main() {
    int n = 10 ;
    int first_num = 0;
    int second_num = 1;
    cout<<first_num<<" "<<second_num<<" ";
    for(int i = 1 ; i <= n ; i++){
        int next_num = first_num + second_num; // adding them to get the next number
        cout<<next_num<<" ";
        //now we need to update first and second num
        first_num = second_num ;  // storing second num to 1st num 
        second_num = next_num; // updating second num with next num 
    }
    return 0;
}